# Generated by Django 5.0.1 on 2024-02-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0002_remove_post_etiquetas_delete_comentario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='extracto',
            field=models.TextField(max_length=300),
        ),
    ]
