# Generated by Django 5.0.1 on 2024-02-03 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0005_alter_post_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='publicado',
            field=models.BooleanField(default=False),
        ),
    ]
