# Generated by Django 5.0.1 on 2024-02-03 03:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0006_post_destacado_post_publicado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
