# Generated by Django 5.0.1 on 2024-02-03 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0007_alter_post_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='destacado',
            new_name='principal',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='publicado',
            new_name='secundarias',
        ),
        migrations.AlterField(
            model_name='post',
            name='extracto',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=models.CharField(max_length=90),
        ),
    ]
