# Generated by Django 5.0.1 on 2024-02-03 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0011_post_imagen_destacada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen_destacada',
            field=models.ImageField(blank=True, null=True, upload_to='imagen_destacada'),
        ),
    ]
