# Generated by Django 5.0.1 on 2024-02-03 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0012_alter_post_imagen_destacada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='imagen_destacada',
        ),
    ]
